### ISSUE TITLE
mix.ngScripts is not a function

### ISSUE THREAD

**Issue by ali-hellani** [hexbridge/laravel-elixir-ng-scripts#1]
Hello,

I have gulp 3.9 installed on my windows machine. **(laravel 5.0)**

i used your simple example here https://www.npmjs.com/package/laravel-elixir-ng-scripts but the following error has produced.

**Note: i have required it at the top.**

```
C:\Users\Leo\Projects\sayidaty-mall\gulpfile.js:6
    mix.ngScripts('scripts.json'); // json file that contains an array
        ^

TypeError: mix.ngScripts is not a function
    at C:\Users\Leo\Projects\sayidaty-mall\gulpfile.js:6:9
    at Elixir (C:\Users\Leo\Projects\sayidaty-mall\node_modules\laravel-elixir\index.js:17:5)
    at Object.<anonymous> (C:\Users\Leo\Projects\sayidaty-mall\gulpfile.js:5:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (c:\Users\Leo\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)

```

**Comment by ali-hellani** [comment]
**ohh i think it is a compatibility issue.**

my installed version of elixir is **3.3.3** but the laravel-elixir-ng-scripts uses **2.3.13** in my case.

And i have noticed in the github page of laravel elixir version 3, they mentioned that:
- Any Laravel Elixir extensions will need to be updated to support version 3.0. Don't worry, it's quick to do so, and removes a lot of boilerplate.
  https://github.com/laravel/elixir/releases

**So, plz, can you take into consideration this case.**

Thanks in advance;

**Comment by deiucanta** [comment]
Hey @ali-hellani,

Would you like to make a pull request with the fixes? :) I'm busy for the next couple of days and I'd love your support on this.

Thanks,
Andrei
